### ISSUE TITLE
rhandsontable

### ISSUE THREAD

**Issue by homerhanumat** [MTstateIntroStats/IntroStatApps#2]
Hello,

This is a very nice app!  You mention in the README that you would like to work with the rhandsontable package to vary the number of rows and columns in data-entry tables.  I was able to accomplish that in the [this Shiny app](https://github.com/homerhanumat/shinyGC/tree/master/SlowAssoc).  I would work up a pull request but I'm not quite if what I did corresponds to what you want.

Regards,
Homer

**Comment by jimrc** [comment]
Glad to know someone saw the app and understands Shiny!
We've realized we could allow the user to set the number of rows and feed it into the rhandsontable call.(columns I want to control for now) 
I guess the real hangup for me was wanting to allow the user to paste in multiple cells in one operation.
With your app (nice! We've not thought about tackling chisquared yet), as with experimentation I've tried, pasting multiple cells from a spreadsheet results in an NA.
The text box seems to work OK, though it's not pretty - it does handle "paste" and it expands to fit any number of rows. 
 I recall seeing some discussion on jrowens rhandsontable pages, and I experimented enough to see that the original handsontable js app does allow pasting in a range of values.

**Comment by homerhanumat** [comment]
Yes, inputting a range of values is not something I ever considered.

**Comment by homerhanumat** [comment]
Jim,

I was on some preliminary list of invitees for an RStudio conference for
Shiny developers.  I recommended that you be invited as well, but since
then the organizers have opened the event to all comers.  Hence you may not
get a direct invitation.

So here's the conference, in case you are interested:

http://www.r-bloggers.com/shiny-developer-conference-stanford-university-january-2016/

It looks mighty useful.  I have decided to go, and apparently so has Daniel
Kaplan of Macalaster College.  He uses Shiny quite a bit for teaching, as
well.

Regards,
Homer

**Comment by jimrc** [comment]
Thanks!  I did get an invitation Thursday and signed up yesterday.
Should be very interesting.  I'm quite interested in 'gadgets' because I've had to copy much code several times to run in each different tabPanel.  I'm hoping gadgets will streamline that process. I know Danny has worked with Randy Pruim and Nick Horton on the mosaic package. Do you know if they will attend?

**Comment by homerhanumat** [comment]
Jim,

There is a Daniel K on the list of attendees:  I figure that's Danny Kaplan.

I'm not sure what Hadley has in mind with gadgets.  I think they might just
be R functions that call up a Shiny app, as in the little package I've
started writing:  https://github.com/homerhanumat/ShinyLocalEdu.

I'm glad to hear that you will attend the conference, and I look forward to
meeting you.  You appear to know an enviable amount of Javascript; I have
been wondering if it would be worth the trouble to learn it myself.  In
particular I'm wondering whether it's feasible to write a Javascript
library of gadgets useful in prob & stat demo apps:  spinners, shufflers,
coin flippers, sampled items popping out of boxes, etc.  Then write an R
interface for this library, so other instructors can incorporate them
easily into their Shiny apps.  I think you might already know the answer to
my question, and if so maybe we can talk about it at the conference.

Homer

**Comment by jimrc** [comment]
Hi Homer,

   I am certainly not a javascript expert, but started learning D3 to 
get nice animations.
   I have the spinner and a "mixer" - drawing balls from a box that I'm 
happy to share.

   Some years ago I did some animation in plain R graphics, but it's 
quite unhandy due to having to erase the trail as you move things.
The svg idea in html5 is really nice for animation - called 
'transitions' in D3.
  Position is just an attribute of an object which can be changed along 
with size, shape, color, rotation.
  The challenge was to set timings and chaining so that one transition 
completed before the next began.

I assume you've seen the Rossman-Chance applets. 
http://www.rossmanchance.com/applets/index.html
Some nice ideas there, and Beth Chance has converted most of them from 
java to javascript, so they do run nicely in a browser.
I don't know if she uses a graphics library, but  they don't look as 
nice to me as D3 or shiny-with-bootstrap.
Next on my list would be a "moveable line" regression demo like you've 
done, but using D3 to show the squared residuals (like Beth has done).

I've not talked to Beth to see how she feels about sharing that work.
I've always figured it's a fun challenge to start from scratch.
They are now using her suite of apps with the newISI book (Tintle  et 
al) http://www.wiley.com/WileyCDA/WileyTitle/productCd-1118956672.html

I hope we can get a group of other 'stat ed' interested folks together 
for discussions at the conference.

Looking forward to meeting you as well,
Jim
